### ISSUE TITLE
Xcode 10.2 / Swift 5 init issue

### ISSUE THREAD

**Issue by aplusm** [tenjin/tenjin-ios-sdk#47]
When using Xcode 10.2 and swift 5, the init(apiToken:) method of the TenjinSDK triggers an error:

**Argument passed to call that takes no arguments**

**Comment by vanner** [comment]
Hi,

1) Can you let me know which version of the SDK you are using?
2) Can you send me a snippet of your sample implementation?  

I also updated our example Swift app here: https://github.com/tenjin/tenjin-ios-sdk-swift

If you're still getting issues, can you send me screenshot/stack trace of the error.

Let me know,
Van

**Comment by aplusm** [comment]
Hi,

1. I'm using TenjinSDK (1.9.0) through cocoapods.
2. My implementation is pretty basic, i'm simply calling:

`
TenjinSDK.init("<MY_KEY>")
`

But i'm getting the following error:

<img width="1245" alt="Screenshot 2019-03-27 at 23 10 06" src="https://user-images.githubusercontent.com/13195720/55115754-90e26600-50e5-11e9-8675-aee16cd906c1.png">

This setup was working correctly up to latest Xcode 10.2 Beta.

**Comment by aplusm** [comment]
Hi,

I'm using TenjinSDK (1.9.0) through cocoapods.
My implementation is pretty basic, i'm simply calling:
TenjinSDK.init("<MY_KEY>")

But i'm getting the following error:

<img width="1230" alt="Screenshot 2019-03-27 at 23 12 53" src="https://user-images.githubusercontent.com/13195720/55115963-1239f880-50e6-11e9-843d-b15f237d0e41.png">

This setup was working correctly up to latest Xcode 10.2 Beta.

**Comment by vanner** [comment]
I pushed up the latest version.  Can you let me know if you continue to see the error after?

**Comment by aplusm** [comment]
The problem is still there after updating to 1.9.0a.
You can trigger this issue in the tenjin-io-sdk-swift by setting Swift Language Version to **Swift 5**.

**Comment by aplusm** [comment]
Do you have any updates on this issue ?

**Comment by vanner** [comment]
I added v1.9.1, which contains alternative `getInstance()` method.  See [example](https://github.com/tenjin/tenjin-ios-sdk-swift/blob/master/tenjin-ios-sdk-swift/ViewController.swift#L15).
